
# from .PSPNet import PSPNet
from .UPerNet_Org import UPerNet_Org_Res50
from .DeepLabV3Plus import DeepLabV3Plus_Res101
from .DeepLabV3Plus import DeepLabV3Plus_Res50
from .AdaptNet_VGG16 import AdaptNet_VGG16
from .DeepLabV3Plus_Res50_withRepHead import DeepLabV3Plus_withRepHead
from .DeepLabV3Plus_Res50_withRepHead_OCT_CLR2 import DeepLabV3Plus_withRepHead_OCT_CLR2
from .DeepLabV3Plus_Res50_withRepHead_OCT_CLR3 import DeepLabV3Plus_withRepHead_OCT_CLR3

